name: Test and Publish Nightingale App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install and Build 🔧
        run: |
          yarn
          yarn bootstrap
          yarn build
      - name: Test 🧪
        run: |
          yarn test
      - name: Build Site 🏗
        run: |
          yarn build-site
          ls -l app/dist
      - name: Deploy Site 🚀
        if: ${{ github.ref == "master" }}
        run: |
          echo "To be implemented"
